src/main/resources/application.yml

application.yml 데이터베이스
Environment variables 설정 추가

[feat]: 프로젝트 세팅

---

src/main/java/gdg/whowantit/entity/Beneficiary.java
src/main/java/gdg/whowantit/entity/Field.java
src/main/java/gdg/whowantit/entity/Funding.java
src/main/java/gdg/whowantit/entity/FundingRelation.java
src/main/java/gdg/whowantit/entity/Post.java
src/main/java/gdg/whowantit/entity/Role.java
src/main/java/gdg/whowantit/entity/Sponsor.java
src/main/java/gdg/whowantit/entity/Status.java
src/main/java/gdg/whowantit/entity/User.java
src/main/java/gdg/whowantit/entity/Volunteer.java
src/main/java/gdg/whowantit/entity/VolunteerRelation.java
src/main/resources/application.yml

10 feat create entity classes

---

src/main/java/gdg/whowantit/entity/BaseEntity.java
src/main/java/gdg/whowantit/entity/Beneficiary.java
src/main/java/gdg/whowantit/entity/Field.java
src/main/java/gdg/whowantit/entity/Funding.java
src/main/java/gdg/whowantit/entity/FundingRelation.java
src/main/java/gdg/whowantit/entity/Post.java
src/main/java/gdg/whowantit/entity/Scrap.java
src/main/java/gdg/whowantit/entity/Sponsor.java
src/main/java/gdg/whowantit/entity/User.java
src/main/java/gdg/whowantit/entity/Volunteer.java
src/main/java/gdg/whowantit/entity/VolunteerRelation.java

[FEAT] Create Entity Classes #2

---

src/main/java/gdg/whowantit/entity/ApprovalStatus.java
src/main/java/gdg/whowantit/entity/Beneficiary.java
src/main/java/gdg/whowantit/entity/Funding.java
src/main/java/gdg/whowantit/entity/Volunteer.java

ApprovalStatus 관련 변경사항 적용
Beneficiary Entity에 원생 현황 관련 칼럼 추가
Funding 게시물에 현재 모금액 관련 칼럼 추가

[FEAT] Create Entity Classes (2)

---

.gitignore
build.gradle
src/main/java/gdg/whowantit/config/PropertyConfig.java
src/main/java/gdg/whowantit/config/SecurityConfig.java
src/main/java/gdg/whowantit/config/SwaggerConfig.java
src/main/resources/application.yml

[feat] swagger 의존성 문제 해결

---

build.gradle
src/main/java/gdg/whowantit/apiPayload/code/status/ErrorStatus.java
src/main/java/gdg/whowantit/config/JwtConfig.java
src/main/java/gdg/whowantit/config/SecurityConfig.java
src/main/java/gdg/whowantit/config/SwaggerConfig.java
src/main/java/gdg/whowantit/controller/UserController.java
src/main/java/gdg/whowantit/converter/UserConverter.java
src/main/java/gdg/whowantit/dto/TokenResponse.java
src/main/java/gdg/whowantit/dto/request/SignInRequestDto.java
src/main/java/gdg/whowantit/dto/request/SignUpRequestDto.java
src/main/java/gdg/whowantit/dto/response/UserResponseDto.java
src/main/java/gdg/whowantit/entity/RefreshToken.java
src/main/java/gdg/whowantit/entity/User.java
src/main/java/gdg/whowantit/repository/BeneficiaryRepository.java
src/main/java/gdg/whowantit/repository/RefreshTokenRepository.java
src/main/java/gdg/whowantit/repository/SponsorRepository.java
src/main/java/gdg/whowantit/repository/UserRepository.java
src/main/java/gdg/whowantit/security/JwtAuthenticationFilter.java
src/main/java/gdg/whowantit/service/TokenService.java
src/main/java/gdg/whowantit/service/UserService.java
src/main/java/gdg/whowantit/util/JwtUtil.java

JWT 이용한 유저 관련 기능 구현
유저 회원가입 기능
유저 로그인 기능
유저 로그아웃 기능
유저 회원 탈퇴 기능
유저 개인 정보 조회 기능
유저 토큰 재발급 기능

[FEAT] 16 user volunteer post 관련 서비스 로직 및 api 개발

---

build.gradle
src/main/java/gdg/whowantit/aws/s3/AmazonS3Manager.java
src/main/java/gdg/whowantit/config/AmazonConfig.java
src/main/java/gdg/whowantit/controller/ImageController.java
src/main/java/gdg/whowantit/service/ImageService/ImageService.java
src/main/java/gdg/whowantit/service/ImageService/ImageServiceImpl.java
src/main/resources/application.yml

#23 
이미지 업로드 API 구현
result값을 웹 url창에 입력하면 나올 것.

[Feat] s3 이용하여 이미지 업로드 API 구현

---

.github/workflows/github-actions.yml

github-actions.yml AWS, JWT 값 추가

[docs] github-actions.yml AWS, JWT 값 추가

---

src/main/java/gdg/whowantit/config/AmazonConfig.java

AmazonConfig 파일 propertySource 추가

[docs] AmazonConfig 파일 propertySource 추가

---

src/main/java/gdg/whowantit/config/AmazonConfig.java
src/main/resources/application.yml

[docs] AmazonConfig 원상태로 복귀

---

.github/workflows/github-actions.yml

[docs] github-action.yml - 환경변수명 변경

[docs] github-action.yml - 환경변수명 변경

---

src/main/java/gdg/whowantit/config/AmazonConfig.java

accessKey, secretKey 직접 환경변수에서 접근하도록 수정

[docs]: accessKey, secretKey 직접 환경변수에서 접근하도록 수정

---

.github/workflows/github-actions.yml
build.gradle
src/main/java/gdg/whowantit/config/AmazonConfig.java

[docs] 환경 변수

---

src/main/java/gdg/whowantit/config/AmazonConfig.java
src/main/resources/application.yml

[FEAT] aws, jwt 관련 환경설정

---

.github/workflows/github-actions.yml
src/main/java/gdg/whowantit/config/AmazonConfig.java

[docs] 환경변수명 재설정

---

Dockerfile

[docs] dockerFile 수정

---

.github/workflows/github-actions.yml
.gitignore
build.gradle

[docs] env 파일 생성

---

build.gradle

docs: build.gradle 수정

---

.github/workflows/github-actions.yml
src/main/resources/application.yml

docs: application.ymle 수정

---

.github/workflows/github-actions.yml
src/main/java/gdg/whowantit/config/AmazonConfig.java

docs:AmazonConfig 수정

---

.github/workflows/github-actions.yml

docs:github-application.yml 수정

---

.github/workflows/github-actions.yml

docs:docker 공간 확보

---

.github/workflows/github-actions.yml

[docs] application.yml 수정

---

.github/workflows/github-actions.yml

[docs]github-actions.yml
